export const GOOGLE_ADS_CONFIG = {
  CONVERSION_ID: 'AW-CONVERSION_ID',
  PHONE_CALL_LABEL: 'CONVERSION_LABEL_PHONE',
  FORM_SUBMISSION_LABEL: 'CONVERSION_LABEL_FORM',
  GA4_ID: 'G-BYQS112WSX',
  REMARKETING_ID: 'G-BYQS112WSX'
} as const;
